// ─── CryptoVault Pro — Shared Data & Constants ───────────────────────────────

export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: 250,
    roi: 5,
    duration: "monthly",
    minDeposit: 250,
    maxDeposit: 999,
    color: "#4A9EFF",
    badge: null,
    features: [
      "5% Monthly ROI",
      "Basic market signals",
      "Email support",
      "Weekly performance report",
      "Access to 3 coin pairs",
      "Manual withdrawal",
    ],
    notIncluded: [
      "AI-powered analysis",
      "Dedicated account manager",
      "Priority withdrawal",
      "Custom strategy",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: 1000,
    roi: 8,
    duration: "monthly",
    minDeposit: 1000,
    maxDeposit: 4999,
    color: "#00D4AA",
    badge: null,
    features: [
      "8% Monthly ROI",
      "Advanced trading signals",
      "Priority email & chat support",
      "Daily performance report",
      "Access to 10 coin pairs",
      "Automated reinvestment",
      "Portfolio tracker",
    ],
    notIncluded: [
      "AI-powered analysis",
      "Dedicated account manager",
      "Custom strategy",
    ],
  },
  {
    id: "pro",
    name: "Pro Trader",
    price: 5000,
    roi: 12,
    duration: "monthly",
    minDeposit: 5000,
    maxDeposit: 14999,
    color: "#7B61FF",
    badge: "Most Popular",
    features: [
      "12% Monthly ROI",
      "Premium trading signals",
      "24/7 live support",
      "Real-time performance dashboard",
      "Access to all coin pairs",
      "Automated reinvestment",
      "AI-powered market analysis",
      "Priority withdrawal (24h)",
      "Risk management tools",
    ],
    notIncluded: [
      "Dedicated account manager",
      "Custom strategy",
    ],
  },
  {
    id: "elite",
    name: "Elite",
    price: 15000,
    roi: 18,
    duration: "monthly",
    minDeposit: 15000,
    maxDeposit: 49999,
    color: "#FFB800",
    badge: "Best Value",
    features: [
      "18% Monthly ROI",
      "Exclusive VIP signals",
      "Dedicated account manager",
      "Real-time dashboard & alerts",
      "All coin pairs + futures",
      "Automated compound interest",
      "Advanced AI analysis suite",
      "Priority withdrawal (12h)",
      "Hedging & risk management",
      "Monthly strategy review",
    ],
    notIncluded: ["Custom trading strategy"],
  },
  {
    id: "titan",
    name: "Titan",
    price: 50000,
    roi: 25,
    duration: "monthly",
    minDeposit: 50000,
    maxDeposit: null,
    color: "#FF6B35",
    badge: "Exclusive",
    features: [
      "25% Monthly ROI",
      "Institutional-grade signals",
      "Personal senior broker",
      "White-glove 24/7 support",
      "All assets + derivatives",
      "Full compound automation",
      "Custom AI trading strategy",
      "Instant withdrawal",
      "Quarterly portfolio audit",
      "OTC trading access",
      "Tax optimization guidance",
    ],
    notIncluded: [],
  },
];

export const MOCK_USERS = [
  { id: "u001", name: "Alex Morgan",    email: "alex@email.com",   plan: "pro",     status: "active",   balance: 18450, invested: 15000, profit: 3450,  joinedAt: "2024-08-14", lastActive: "2026-02-22" },
  { id: "u002", name: "Sarah Okafor",   email: "sarah@email.com",  plan: "elite",   status: "active",   balance: 52800, invested: 45000, profit: 7800,  joinedAt: "2024-06-02", lastActive: "2026-02-21" },
  { id: "u003", name: "James Chen",     email: "james@email.com",  plan: "starter", status: "active",   balance: 290,   invested: 250,   profit: 40,    joinedAt: "2025-01-18", lastActive: "2026-02-20" },
  { id: "u004", name: "Priya Sharma",   email: "priya@email.com",  plan: "growth",  status: "suspended",balance: 1180,  invested: 1000,  profit: 180,   joinedAt: "2024-11-05", lastActive: "2026-01-30" },
  { id: "u005", name: "Marcus Webb",    email: "marcus@email.com", plan: "titan",   status: "active",   balance: 78500, invested: 50000, profit: 28500, joinedAt: "2024-03-22", lastActive: "2026-02-22" },
  { id: "u006", name: "Yuki Tanaka",    email: "yuki@email.com",   plan: "pro",     status: "active",   balance: 6200,  invested: 5000,  profit: 1200,  joinedAt: "2025-05-10", lastActive: "2026-02-19" },
  { id: "u007", name: "Linda Diallo",   email: "linda@email.com",  plan: "growth",  status: "pending",  balance: 0,     invested: 0,     profit: 0,     joinedAt: "2026-02-20", lastActive: "2026-02-20" },
  { id: "u008", name: "David Kim",      email: "david@email.com",  plan: "elite",   status: "active",   balance: 21000, invested: 15000, profit: 6000,  joinedAt: "2024-09-01", lastActive: "2026-02-22" },
];

export const MOCK_TRANSACTIONS = [
  { id: "tx001", userId: "u001", user: "Alex Morgan",   type: "deposit",    amount: 15000, status: "completed", date: "2026-02-01", method: "USDT",    plan: "pro"     },
  { id: "tx002", userId: "u002", user: "Sarah Okafor",  type: "profit",     amount: 7800,  status: "completed", date: "2026-02-15", method: "System",   plan: "elite"   },
  { id: "tx003", userId: "u003", user: "James Chen",    type: "deposit",    amount: 250,   status: "completed", date: "2026-01-18", method: "Bitcoin",  plan: "starter" },
  { id: "tx004", userId: "u005", user: "Marcus Webb",   type: "withdrawal", amount: 10000, status: "pending",   date: "2026-02-22", method: "USDT",    plan: "titan"   },
  { id: "tx005", userId: "u006", user: "Yuki Tanaka",   type: "profit",     amount: 1200,  status: "completed", date: "2026-02-10", method: "System",   plan: "pro"     },
  { id: "tx006", userId: "u001", user: "Alex Morgan",   type: "withdrawal", amount: 2000,  status: "completed", date: "2026-02-18", method: "Ethereum", plan: "pro"     },
  { id: "tx007", userId: "u008", user: "David Kim",     type: "deposit",    amount: 15000, status: "completed", date: "2025-09-01", method: "Bitcoin",  plan: "elite"   },
  { id: "tx008", userId: "u004", user: "Priya Sharma",  type: "withdrawal", amount: 500,   status: "rejected",  date: "2026-01-28", method: "USDT",    plan: "growth"  },
  { id: "tx009", userId: "u007", user: "Linda Diallo",  type: "deposit",    amount: 1000,  status: "pending",   date: "2026-02-20", method: "Bitcoin",  plan: "growth"  },
  { id: "tx010", userId: "u002", user: "Sarah Okafor",  type: "withdrawal", amount: 5000,  status: "pending",   date: "2026-02-22", method: "USDT",    plan: "elite"   },
];

export const CRYPTO_PRICES = [
  { symbol: "BTC",  name: "Bitcoin",   price: 98420.50, change: 2.34,  color: "#FFB800" },
  { symbol: "ETH",  name: "Ethereum",  price: 3241.80,  change: -1.12, color: "#7B61FF" },
  { symbol: "BNB",  name: "BNB",       price: 412.30,   change: 0.87,  color: "#FFD700" },
  { symbol: "SOL",  name: "Solana",    price: 187.40,   change: 5.21,  color: "#00D4AA" },
  { symbol: "XRP",  name: "Ripple",    price: 0.8420,   change: -0.45, color: "#4A9EFF" },
  { symbol: "ADA",  name: "Cardano",   price: 0.6180,   change: 1.93,  color: "#4A9EFF" },
  { symbol: "DOGE", name: "Dogecoin",  price: 0.1842,   change: 3.67,  color: "#FFB800" },
  { symbol: "DOT",  name: "Polkadot",  price: 9.420,    change: -2.18, color: "#FF6B35" },
];

export const ADMIN_STATS = {
  totalUsers: 248,
  activeUsers: 201,
  totalDeposited: 1284500,
  totalProfitPaid: 312800,
  pendingWithdrawals: 12,
  monthlyRevenue: 89400,
  planDistribution: {
    starter: 82,
    growth: 74,
    pro: 52,
    elite: 28,
    titan: 12,
  },
};
